-- =============================================================================
-- SUPERSEDED / INTENTIONALLY DISABLED — do not restore.
-- =============================================================================
-- This file was an ABANDONED first attempt at multi-tenancy (a per-row `org_id`
-- column + `current_org_id()` + a RESTRICTIVE `org_isolation` policy on ~25
-- tables). The LIVE tenancy model is the `20260529_saas_01..09` series
-- (organization_id + memberships + is_org_member()); this approach was never
-- adopted and is referenced nowhere in the application code.
--
-- Running its original body on a FRESH database bricks the app:
-- create_organization_with_owner never sets users.org_id, so current_org_id()
-- returns NULL and the RESTRICTIVE policy then rejects every row/insert on
-- drivers, vehicles, settlements, etc. It also DROPs the `events` table and adds
-- an `org_id` column that shadows organization_id.
--
-- The body has been removed so this migration is now a safe no-op. The original
-- is preserved in git history. If any environment previously ran the original,
-- clean up the orphans there: DROP the `org_isolation` policies, the
-- `trg_set_org_id` triggers, and the stray `org_id` columns.
--
-- Neutralized 2026-07-09 during the security audit (see security-audit-2026-07).
-- =============================================================================

SELECT 'Superseded tenancy migration — intentionally a no-op.' AS message;
